apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.0.128 # master ip
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.26.5 # 설치한 kubeadm, kubelet, kubectl과 동일한 버전
controlPlaneEndpoint: 10.0.0.128:6443 # master ip 지정, port는 반드시 6443
# imageRepository: k8s.gcr.io 1.25버전 이후로는 registry.k8s.io로 변경되었음
networking:
  serviceSubnet: 10.96.0.0/12 # 사용할 service의 ip cidr
  podSubnet: 10.244.0.0/16 # 사용할 pod의 ip cidr
apiServer:
  certSANs:
    - "119.197.217.80"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
