name: Commit Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - release
      - production

jobs:
  lint:
    runs-on: ubuntu-latest
    name: check commit messages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout lint config file
        uses: actions/checkout@v3
        with:
          repository: new-caledonia/.github
          path: github-configs
          ref: main

      - name: Copy commitlint config files to root dir
        run: |
          cp -f github-configs/config/commitlint/* .

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Validate commits
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --verbose